### ISSUE TITLE
Memo generates access violation error

### ISSUE THREAD

**Issue by Ariel-MN** [Embarcadero/DelphiVCL4Python#18] opened 2022-02-18 00:26 UTC
The Memo component generates an access violation error after changing the style of the application.

Example code:

```py
import os
from delphivcl import *

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

class MainForm(Form):

    def __init__(self, owner):
        self.Caption = "Test Memo"
        self.SetBounds(10, 10, 500, 400)
        self.Position = "poScreenCenter"

        # Memo component
        self.txtMemo = Memo(self)
        self.txtMemo.SetProps(Parent=self)
        self.txtMemo.SetBounds(10, 40, 300, 100)

        # Auto-load new style
        self.__sm = StyleManager()
        self.__load_style()

    def __load_style(self):
        self.__sm.LoadFromFile(os.path.join(BASE_DIR, "Windows11_Modern_Dark.vsf"))
        self.__sm.SetStyle(self.__sm.StyleNames[1])

def main():
    Application.Initialize()
    Application.Title = "Checking DelphiVCL4Python"
    Main = MainForm(Application)
    Main.Show()
    Application.Run()
    Main.Destroy()

if __name__ == '__main__':
    main()
```

**Comment by lmbelo** [comment] 2022-02-18 12:02
@Ariel-MN thank you to report. I will have a look on it.

**Comment by Priyatham10** [comment] 2022-02-19 06:22
I tested with the same code you sent and found no such error. I even added one more style and printed them to the Memo. Please find the code and the GUI output result image.
```python
import os
from delphivcl import *

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

class MainForm(Form):

    def __init__(self, owner):
        self.Caption = "Test Memo"
        self.SetBounds(10, 10, 500, 400)
        self.Position = "poScreenCenter"

        # Memo component
        self.txtMemo = Memo(self)
        self.txtMemo.SetProps(Parent=self)
        self.txtMemo.SetBounds(10, 40, 300, 100)

        # Auto-load new style
        self.__sm = StyleManager()
        self.__load_style()

        self.txtMemo.Lines.Add(f"Number of loaded styles: {len(self.__sm.StyleNames)}")
        self.txtMemo.Lines.Add("The loaded Styles are:")
        self.txtMemo.Lines.Add(self.__sm.StyleNames[0])
        self.txtMemo.Lines.Add(self.__sm.StyleNames[1])
        self.txtMemo.Lines.Add(self.__sm.StyleNames[2])

    def __load_style(self):
        self.__sm.LoadFromFile(os.path.join(BASE_DIR, "Windows10SlateGray.vsf"))
        self.__sm.LoadFromFile(os.path.join(BASE_DIR, "SapphireKamri.vsf"))
        self.__sm.SetStyle(self.__sm.StyleNames[2])

def main():
    Application.Initialize()
    Application.Title = "Checking DelphiVCL4Python"
    Main = MainForm(Application)
    Main.Show()
    Application.Run()
    Main.Destroy()

if __name__ == '__main__':
    main()
```
![image](https://user-images.githubusercontent.com/17174106/154789134-841c66da-1fe6-4f74-a124-8771ae09451c.png)

The error is because you might not have permission to access the `Windows11_Modern_Dark.vsf` style file.

**Comment by Ariel-MN** [comment] 2022-02-19 07:26
I have all users full permission on the style file properties and have no problem using the same style file in an app with other components.

The application runs but it is impossible to interact with it as it generates this error that keeps reappearing in a loop.
![err](https://user-images.githubusercontent.com/48733790/154791259-f0bf3e73-b09c-41b2-998c-61bbc8077da7.png)

**Comment by Priyatham10** [comment] 2022-02-19 08:45
Okay, fine. Thanks for more details. @Ariel-MN you meant that this error is getting generated when using the `Memo` component only and runs fine with other components? And did you try any other styles with the `Memo` component to test their working status with the `Memo`?

**Comment by Ariel-MN** [comment] 2022-02-19 08:54
Absolutely. The error only happens with the Memo component and not with others and I have tried with several styles obtaining the same result.

**Comment by Priyatham10** [comment] 2022-02-19 09:04
Weird! You can see it running without any issue in the reply I posted above right? Maybe, we'll need to simulate your exact environment (OS and python version) and try it once. Will get back with more news as we figure out anything new on this.

Thank you so much and we appreciate you keep trying and testing more.

**Comment by lmbelo** [comment] 2022-02-19 11:21
Most likely something regarding the Win 11. Are you using Python x86 or x64?

**Comment by Ariel-MN** [comment] 2022-02-19 18:06
@Priyatham10 You are very welcome. Unfortunately your script produced the same result as mine in both of my environments. 
@lmbelo I am using Python x86. I can confirm that it is not related to the version of Windows, I have tried it on another PC and am running into the same issue in this environment:

- Windows 10
- Python 3.9.7
- delphivcl 0.1.34

**Comment by lmbelo** [comment] 2022-02-19 18:09
@Ariel-MN I will try to simulate in a similar environment as yours.

**Comment by lmbelo** [comment] 2022-03-23 23:28
@Ariel-MN are you still facing such error? I can't reproduce it here.

**Comment by Ariel-MN** [comment] 2022-03-24 08:50
@lmbelo yes, i still have the same problem.

**Comment by lmbelo** [comment] 2022-03-24 20:42
@Ariel-MN I really can't reproduce this issue. I have tried in Win 11 and even in Win 10, it's working in both.

**Comment by Ariel-MN** [comment] 2022-03-24 21:12
@lmbelo If it can be useful I can offer you access through teamviewer to one of my environments.

**Comment by lmbelo** [comment] 2022-03-24 21:16
@Ariel-MN  It would be great.
Please, send an e-mail to lucas.belo@live.com to schedule a date.
Thank you for your interest and support.

**Comment by lmbelo** [comment] 2022-03-26 21:00
I was finally able to reproduce this issue under Python x64 architecture. It does run well under Python x86.

**Comment by lmbelo** [comment] 2022-03-29 21:41
I realized this is something regarding the new ComCtrls library. It occurs when the SystemStyle is enable, which may happen when using a comctrls32.dll >= 393216.
We have a ticket at https://quality.embarcadero.com/browse/RSP-37835.
I will provide a workaround soon.

**Comment by lmbelo** [comment] 2022-03-29 23:17
I have the workaround done. I hope to get it available in our next release.

**Comment by Ariel-MN** [comment] 2022-03-30 06:57
That's very good news. I'll be waiting for the new version. Thank you.

**Comment by lmbelo** [comment] 2022-04-08 16:46
@Ariel-MN it was solved in Delphi 11.1, as related in the [ticket](https://quality.embarcadero.com/browse/RSP-37835), then I don't need to proceed with my workaround.
have in mind if you release your own module using Delphi 11 the error will persist.

I'm working on a new release and it will be available soon.

**Comment by Ariel-MN** [comment] 2022-04-12 21:10
@lmbelo, fixed in version 1.0.39, although this new version seems to have broken compatibility with the new Classe added in 1.0.38 TNumberBox.

**Comment by lmbelo** [comment] 2022-04-12 21:15
Thank you to report @Ariel-MN. I will investigate this case.

**Comment by lmbelo** [comment] 2022-04-13 18:42
@Ariel-MN a new version containing the TNumberBox fix is out. Can you try again?

**Comment by Ariel-MN** [comment] 2022-04-13 20:37
@lmbelo, now everything works perfectly. Even other High DPI related issues have been fixed with Delphi 11.

**Comment by lmbelo** [comment] 2022-04-13 22:11
> @lmbelo, now everything works perfectly. Even other High DPI related issues have been fixed with Delphi 11.

Fabulous 🚀

Can we close this issue?

**Comment by Ariel-MN** [comment] 2022-04-13 23:49
Sure, go ahead.

**Closed** 2022-04-14 21:57 UTC
Labels: bug
